@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:sk_pqc/sk_pqc.dart';
import 'package:sk_pqc/src/mlkem_provider_ffi.dart';
import 'package:test/test.dart';

Uint8List hex(String h) {
  final out = Uint8List(h.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(h.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String toHex(Uint8List b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

void main() {
  // The native FFI tests need liboqs at runtime. Skip cleanly if absent so the
  // suite still passes on machines without the binary.
  bool liboqsAvailable() {
    try {
      LiboqsMlKem768();
      return true;
    } catch (_) {
      return false;
    }
  }

  final haveOqs = liboqsAvailable();

  group('liboqs ML-KEM-768 backend (FFI)', () {
    test('reports its impl name', () {
      final b = LiboqsMlKem768();
      expect(b.implName, contains('liboqs'));
    }, skip: haveOqs ? false : 'liboqs not available');

    test('FIPS 203 sizes + self round-trip', () async {
      final b = LiboqsMlKem768();
      final (pk, sk) = await b.keygen();
      expect(pk.length, SkPqcSizes.mlkem768PublicKey);
      expect(sk.length, SkPqcSizes.mlkem768SecretKey);
      final (ct, ss) = await b.encapsulate(pk);
      expect(ct.length, SkPqcSizes.mlkem768Ciphertext);
      expect(ss.length, SkPqcSizes.mlkem768SharedSecret);
      final ss2 = await b.decapsulate(ct, sk);
      expect(toHex(ss2), equals(toHex(ss)));
    }, skip: haveOqs ? false : 'liboqs not available');

    test('KAT: decapsulating the FIPS-203 vector ct yields the standard ss',
        () async {
      // From test_vectors: the ML-KEM-768 leg was generated by liboqs against
      // the NIST ACVP keyGen KAT (seed d||z). Decapsulation is deterministic,
      // so any conformant impl recovers the same shared secret.
      final v = jsonDecode(
        File('test_vectors/hybrid_kem_x25519_mlkem768.json').readAsStringSync(),
      ) as Map<String, dynamic>;
      final ml = v['legs']['mlkem768'] as Map<String, dynamic>;
      final b = LiboqsMlKem768();
      final ss = await b.decapsulate(
        hex(ml['ciphertext'] as String),
        hex(ml['secret_key'] as String),
      );
      expect(toHex(ss), equals(ml['shared_secret']));
    }, skip: haveOqs ? false : 'liboqs not available');
  });

  group('HybridKem (native, liboqs) — interop vector + round-trips', () {
    HybridKemImpl kem() => HybridKemImpl(mlkemBackend: LiboqsMlKem768());

    test('cross-impl interop vector: decapsulate → expected shared secret',
        () async {
      final v = jsonDecode(
        File('test_vectors/hybrid_kem_x25519_mlkem768.json').readAsStringSync(),
      ) as Map<String, dynamic>;
      final h = v['hybrid'] as Map<String, dynamic>;
      final ss = await kem().decapsulate(
        hex(h['ciphertext'] as String),
        hex(h['private_key'] as String),
      );
      expect(toHex(ss), equals(h['shared_secret']),
          reason:
              'Dart native hybrid decap must match the Python-anchored vector');
    }, skip: haveOqs ? false : 'liboqs not available');

    test('full round-trip: generate → encapsulate → decapsulate', () async {
      final k = kem();
      final kp = await k.generateKeyPair();
      expect(kp.publicKey.length, SkPqcSizes.hybridPublicKey);
      expect(kp.privateKey.length, SkPqcSizes.hybridPrivateKey);
      final enc = await k.encapsulate(kp.publicKey);
      expect(enc.ciphertext.length, SkPqcSizes.hybridCiphertext);
      expect(enc.sharedSecret.length, 32);
      final ss = await k.decapsulate(enc.ciphertext, kp.privateKey);
      expect(toHex(ss), equals(toHex(enc.sharedSecret)));
    }, skip: haveOqs ? false : 'liboqs not available');

    test('two encapsulations to same pk give different ct + secrets', () async {
      final k = kem();
      final kp = await k.generateKeyPair();
      final a = await k.encapsulate(kp.publicKey);
      final b = await k.encapsulate(kp.publicKey);
      expect(toHex(a.ciphertext), isNot(equals(toHex(b.ciphertext))));
      expect(toHex(a.sharedSecret), isNot(equals(toHex(b.sharedSecret))));
    }, skip: haveOqs ? false : 'liboqs not available');

    test('malformed inputs throw SkPqcError, never crash', () async {
      final k = kem();
      final kp = await k.generateKeyPair();
      // wrong-length public key
      expect(() => k.encapsulate(Uint8List(100)), throwsA(isA<SkPqcError>()));
      // wrong-length ciphertext
      expect(() => k.decapsulate(Uint8List(10), kp.privateKey),
          throwsA(isA<SkPqcError>()));
      // wrong-length private key
      final enc = await k.encapsulate(kp.publicKey);
      expect(() => k.decapsulate(enc.ciphertext, Uint8List(50)),
          throwsA(isA<SkPqcError>()));
    }, skip: haveOqs ? false : 'liboqs not available');

    test('tampered ML-KEM ciphertext → implicit rejection (different secret)',
        () async {
      // FIPS 203 implicit rejection: a corrupt ML-KEM ct does not throw; it
      // yields a pseudo-random ss that simply will not match. The hybrid secret
      // therefore differs from the legitimate one.
      final k = kem();
      final kp = await k.generateKeyPair();
      final enc = await k.encapsulate(kp.publicKey);
      final tampered = Uint8List.fromList(enc.ciphertext);
      // flip a byte inside the ML-KEM region (after the 32-B x25519 prefix)
      tampered[100] ^= 0xff;
      final ss = await k.decapsulate(tampered, kp.privateKey);
      expect(toHex(ss), isNot(equals(toHex(enc.sharedSecret))));
    }, skip: haveOqs ? false : 'liboqs not available');
  });

  if (!haveOqs) {
    test('liboqs NOT available — native tests skipped (CI must provide it)', () {
      stderr.writeln(
        'WARNING: liboqs not loadable; native FFI tests skipped. '
        'Set SK_PQC_LIBOQS or install liboqs to exercise them.',
      );
      expect(true, isTrue);
    });
  }
}
